### ISSUE TITLE
Tile is grey

### ISSUE THREAD

**Issue by reynoldtan** [TripalCultivate/TripalCultivate-Theme#17]
A temporary css rule that set the background of tiles to grey was added to help visualize tiles while development. A note was added to this rule to remove it when no longer required. Instead of deleting this rule, convert it to a default background color of each tile using the default color of the base theme (color variable). If no background color set for a tile in the interface, use the color variable otherwise override with the colour set for the tile.

![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/532ed430-0970-4f84-a700-6c6e6df9c61b)

**Comment by laceysanderson** [comment]
Yes! And there are actually a number of variables based on the default colour so you can make each tile a different colour 😍
